### ISSUE TITLE
Compiler error: `Size` and `Size` have similar names, but are actually distinct types

### ISSUE THREAD

**Issue by pol-epsevg** [embedded-graphics/eg-seven-segment#16]
Tried creating a digit by copy-pasting the example on the docs and I get the following error:

```
error[E0308]: mismatched types
  --> src/main.rs:58:21
   |
58 |         .digit_size(Size::new(10, 20)) // digits are 10x20 pixels
   |          ---------- ^^^^^^^^^^^^^^^^^ expected `Size`, found a different `Size`
   |          |
   |          arguments to this method are incorrect
   |
   = note: `Size` and `Size` have similar names, but are actually distinct types
   
   note: `Size` is defined in crate `embedded_graphics_core`
   |
65 | pub struct Size {
   | ^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `embedded_graphics_core` are being used?
```

Happens with both of these:
```
embedded_graphics::prelude::Size::new()
embedded_graphics_core::prelude::Size::new()
```

Has `embedded_graphics` maybe had breaking changes to the `Size` struct causing the error? or am I missing something?

## Code I used
```rs
    let style = SevenSegmentStyleBuilder::new()
        .digit_size(embedded_graphics_core::prelude::Size::new(10, 20)) // digits are 10x20 pixels
        .digit_spacing(5)
        .segment_width(5)
        .segment_color(Rgb666::GREEN)
        .build();
```

It also says the following for `Rgb666` as well as `Rgb888` from the example:
```
the trait `embedded_graphics_core::pixelcolor::PixelColor` is not implemented for `embedded_graphics::pixelcolor::Rgb666`
```

**Comment by pol-epsevg** [comment]
I cloned the repository and updated the `embedded-graphics` key in the `cargo.toml` to the latest one. My sketch now works. Tell me if I should make a merge request bumping all the versions to latest.

**Comment by rfuest** [comment]
> I cloned the repository and updated the `embedded-graphics` key in the `cargo.toml` to the latest one. My sketch now works. Tell me if I should make a merge request bumping all the versions to latest.

That would be great. I can create a new release with e-g 0.8 support after the PR is merged.

**Comment by rfuest** [comment]
`eg-seven-segment` 0.2.0 is now available on crates.io. Thanks for bumping the dependencies.
